require 'typicode/resource'
require 'typicode/resources/album'
require 'typicode/resources/comment'
require 'typicode/resources/photo'
require 'typicode/resources/post'
require 'typicode/resources/todo'
require 'typicode/resources/user'
